---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: auditd
data:
  chart_name: auditd
  release: auditd
  namespace: kube-system
  source:
    location: http://172.17.0.1:8080/helm_charts/stx-platform/auditd-1.0.0.tgz
    subpath: auditd
    type: tar
    reference: master
  wait:
    timeout: 1800
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            app: auditd
  dependencies: []
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: auditd
data:
  description: "StarlingX AUDITD"
  sequenced: false
  chart_group:
    - auditd
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: auditd-manifest
data:
  release_prefix: ns
  chart_groups:
    - auditd
