---
- project:
    vars:
      ensure_tox_version: '<4'
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-auditd-tox-py39
        - k8sapp-auditd-tox-flake8
        - k8sapp-auditd-tox-pylint
        - k8sapp-auditd-tox-metadata
        - k8sapp-auditd-tox-bandit
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-auditd-tox-py39
        - k8sapp-auditd-tox-flake8
        - k8sapp-auditd-tox-pylint
        - k8sapp-auditd-tox-metadata
        - k8sapp-auditd-tox-bandit

- job:
    name: k8sapp-auditd-tox-py39
    parent: openstack-tox-py39
    description: |
            Run py39 test for k8sapp_auditd
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-auditd/*
    vars:
      tox_extra_args: -c python3-k8sapp-auditd/k8sapp_auditd/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-auditd-tox-flake8
    parent: tox
    description: |
            Run flake8 test for k8sapp_auditd
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-auditd/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-auditd/k8sapp_auditd/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-auditd-tox-pylint
    parent: tox
    description: |
            Run pylint test for k8sapp_auditd
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-auditd/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-auditd/k8sapp_auditd/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-auditd-tox-metadata
    parent: tox
    description: |
            Run metadata test for k8sapp_auditd
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-auditd/*
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-auditd/k8sapp_auditd/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-auditd-tox-bandit
    parent: tox
    description: |
            Run bandit test for k8sapp_auditd
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-auditd/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c python3-k8sapp-auditd/k8sapp_auditd/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'
