apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name_auditd }}
data:
  auditd.conf: {{ toYaml .Values.auditdconf | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name_auditd_rules }}
data:
  audit.rules: {{ toYaml .Values.auditdrules | indent 2 }}
