apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "audit.fullname" . }}
  labels:
    app: {{ include "audit.name" . }}
    chart: {{ include "audit.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "audit.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "audit.name" . }}
        release: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 1000 | quote }}
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: {{ include "audit.name" . }}
        image: '{{ .Values.image.repository }}:{{ include "audit.image.tag" . }}'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
        - name: varlog
          mountPath: /var/log/audit
        - name: auditd-etc-config-vol
          mountPath: /etc/audit/auditd.conf
          subPath: auditd.conf
        - name: auditd-etc-rules-vol
          mountPath: /etc/audit/rules.d
        stdin: true
        tty: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/audit
      - name: auditd-etc-config-vol
        configMap:
          name: {{ .Values.configmap.name_auditd }}
          items:
          - key: "auditd.conf"
            path: "auditd.conf"
      - name: auditd-etc-rules-vol
        configMap:
          name: {{ .Values.configmap.name_auditd_rules }}
          items:
          - key: audit.rules
            path: audit.rules
      imagePullSecrets:
      - name: default-registry-key
